name: "@tpluscode/sparql-builder"

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [ '12', '13' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
